import nodemailer from "nodemailer";
import { db } from "../db/index.js";

interface EmailConfig {
  host: string;
  port: number;
  user: string;
  pass: string;
  from: string;
}

function getConfig(orgId: string): EmailConfig | null {
  const org = db.prepare("SELECT settings FROM organizations WHERE id = ?").get(orgId) as any;
  if (!org?.settings) return null;
  try {
    const s = JSON.parse(org.settings);
    if (!s.smtpHost) return null;
    return {
      host: s.smtpHost,
      port: parseInt(s.smtpPort || "587"),
      user: s.smtpUser || "",
      pass: s.smtpPass || "",
      from: s.smtpFrom || "noreply@dialclear.com",
    };
  } catch {
    return null;
  }
}

export async function sendEmail(orgId: string, to: string | string[], subject: string, html: string, attachments?: any[]) {
  const config = getConfig(orgId);
  if (!config) {
    console.log(`[Email] No SMTP config for org ${orgId}, skipping email`);
    return;
  }

  const transporter = nodemailer.createTransport({
    host: config.host,
    port: config.port,
    secure: config.port === 465,
    auth: config.user ? { user: config.user, pass: config.pass } : undefined,
  });

  const recipients = Array.isArray(to) ? to.join(", ") : to;
  await transporter.sendMail({
    from: config.from,
    to: recipients,
    subject,
    html,
    attachments,
  });
  console.log(`[Email] Sent "${subject}" to ${recipients}`);
}

export async function sendDailyReportEmail(orgId: string, reportData: any) {
  const rows = db.prepare("SELECT * FROM daily_reports WHERE organization_id = ? AND is_active = 1").all(orgId) as any[];
  for (const setting of rows) {
    const recipients = (() => { try { return JSON.parse(setting.recipients); } catch { return []; } })();
    if (!recipients.length) continue;

    const totalCalls = reportData?.totalCalls || 0;
    const answeredCalls = reportData?.answeredCalls || 0;
    const totalCost = reportData?.totalCost || "0.00";

    const html = `
      <h2>Daily Report — DialClear</h2>
      <table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;width:100%;max-width:600px">
        <tr><th>Metric</th><th>Value</th></tr>
        <tr><td>Total Calls</td><td>${totalCalls}</td></tr>
        <tr><td>Answered Calls</td><td>${answeredCalls}</td></tr>
        <tr><td>Answer Rate</td><td>${totalCalls > 0 ? Math.round(answeredCalls / totalCalls * 100) : 0}%</td></tr>
        <tr><td>Total Cost</td><td>$${totalCost}</td></tr>
      </table>
      <p style="color:#666;font-size:12px">Generated by DialClear</p>
    `;

    await sendEmail(orgId, recipients, `Daily Report — ${new Date().toLocaleDateString()}`, html);
  }
}

export async function sendInvoiceNotification(orgId: string, invoiceId: string) {
  const invoice = db.prepare("SELECT * FROM invoices WHERE id = ? AND organization_id = ?").get(invoiceId, orgId) as any;
  if (!invoice) return;

  const org = db.prepare("SELECT * FROM organizations WHERE id = ?").get(orgId) as any;
  const users = db.prepare("SELECT email FROM users WHERE organization_id = ?").all(orgId) as any[];
  const emails = users.map((u: any) => u.email).filter(Boolean);
  if (!emails.length) return;

  const html = `
    <h2>Invoice ${invoice.invoice_number}</h2>
    <p>Amount: <strong>$${invoice.total_amount.toFixed(2)}</strong></p>
    <p>Status: ${invoice.status}</p>
    <p>Due: ${invoice.due_date ? new Date(invoice.due_date).toLocaleDateString() : "N/A"}</p>
    <hr/>
    <p style="color:#666;font-size:12px">DialClear Billing</p>
  `;

  await sendEmail(orgId, emails, `Invoice ${invoice.invoice_number} — $${invoice.total_amount.toFixed(2)}`, html);
}
